### ISSUE TITLE
Error when attaching a file

### ISSUE THREAD

**Issue by afred** [WGBH/hydradam2#12]
`Invalid argument - connect(2) for [fe80::1%lo0]:6379`
![image](https://cloud.githubusercontent.com/assets/1507490/10952659/e7c6d1ae-8311-11e5-9962-3f3763b240cd.png)

stack trace
```
redis (3.2.1) lib/redis/connection/ruby.rb:129:in `connect_nonblock'
redis (3.2.1) lib/redis/connection/ruby.rb:129:in `rescue in connect_addrinfo'
redis (3.2.1) lib/redis/connection/ruby.rb:121:in `connect_addrinfo'
redis (3.2.1) lib/redis/connection/ruby.rb:162:in `block in connect'
redis (3.2.1) lib/redis/connection/ruby.rb:160:in `each'
redis (3.2.1) lib/redis/connection/ruby.rb:160:in `each_with_index'
redis (3.2.1) lib/redis/connection/ruby.rb:160:in `connect'
redis (3.2.1) lib/redis/connection/ruby.rb:211:in `connect'
redis (3.2.1) lib/redis/client.rb:322:in `establish_connection'
redis (3.2.1) lib/redis/client.rb:94:in `block in connect'
redis (3.2.1) lib/redis/client.rb:279:in `with_reconnect'
redis (3.2.1) lib/redis/client.rb:93:in `connect'
redis (3.2.1) lib/redis/client.rb:350:in `ensure_connected'
redis (3.2.1) lib/redis/client.rb:207:in `block in process'
redis (3.2.1) lib/redis/client.rb:292:in `logging'
redis (3.2.1) lib/redis/client.rb:206:in `process'
redis (3.2.1) lib/redis/client.rb:112:in `call'
redis (3.2.1) lib/redis.rb:2263:in `block in script'
redis (3.2.1) lib/redis.rb:37:in `block in synchronize'
/Users/andrew_myers/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
redis (3.2.1) lib/redis.rb:37:in `synchronize'
redis (3.2.1) lib/redis.rb:2262:in `script'
redlock (0.1.3) lib/redlock/client.rb:117:in `load_scripts'
redlock (0.1.3) lib/redlock/client.rb:101:in `initialize'
redlock (0.1.3) lib/redlock/client.rb:23:in `new'
redlock (0.1.3) lib/redlock/client.rb:23:in `block in initialize'
redlock (0.1.3) lib/redlock/client.rb:21:in `map'
redlock (0.1.3) lib/redlock/client.rb:21:in `initialize'
/Users/andrew_myers/.rvm/gems/ruby-2.2.0/bundler/gems/curation_concerns-80bab1548b06/curation_concerns-models/app/services/curation_concerns/lock_manager.rb:13:in `new'
/Users/andrew_myers/.rvm/gems/ruby-2.2.0/bundler/gems/curation_concerns-80bab1548b06/curation_concerns-models/app/services/curation_concerns/lock_manager.rb:13:in `initialize'
/Users/andrew_myers/.rvm/gems/ruby-2.2.0/bundler/gems/curation_concerns-80bab1548b06/curation_concerns-models/app/actors/curation_concerns/file_set_actor.rb:183:in `new'
/Users/andrew_myers/.rvm/gems/ruby-2.2.0/bundler/gems/curation_concerns-80bab1548b06/curation_concerns-models/app/actors/curation_concerns/file_set_actor.rb:183:in `lock_manager'
/Users/andrew_myers/.rvm/gems/ruby-2.2.0/bundler/gems/curation_concerns-80bab1548b06/curation_concerns-models/app/actors/curation_concerns/file_set_actor.rb:179:in `acquire_lock_for'
/Users/andrew_myers/.rvm/gems/ruby-2.2.0/bundler/gems/curation_concerns-80bab1548b06/curation_concerns-models/app/actors/curation_concerns/file_set_actor.rb:162:in `attach_file_to_work'
/Users/andrew_myers/.rvm/gems/ruby-2.2.0/bundler/gems/curation_concerns-80bab1548b06/curation_concerns-models/app/actors/curation_concerns/file_set_actor.rb:44:in `create_metadata'
/Users/andrew_myers/.rvm/gems/ruby-2.2.0/bundler/gems/curation_concerns-80bab1548b06/app/controllers/concerns/curation_concerns/file_sets_controller_behavior.rb:173:in `process_file'
/Users/andrew_myers/.rvm/gems/ruby-2.2.0/bundler/gems/curation_concerns-80bab1548b06/app/controllers/concerns/curation_concerns/file_sets_controller_behavior.rb:44:in `create_from_upload'
/Users/andrew_myers/.rvm/gems/ruby-2.2.0/bundler/gems/curation_concerns-80bab1548b06/app/controllers/concerns/curation_concerns/file_sets_controller_behavior.rb:31:in `create'
actionpack (4.2.4) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.4) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.4) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.4) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.4) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.4) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.4) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.4) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.4) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.4) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.4) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.4) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.4) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.4) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.4) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.4) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.4) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.4) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.4) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `call'
actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:45:in `serve'
actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.4) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
active-fedora (9.6.1) lib/active_fedora/ldp_cache.rb:26:in `call'
activerecord (4.2.4) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.4) lib/rails/engine.rb:518:in `call'
railties (4.2.4) lib/rails/application.rb:165:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
/Users/andrew_myers/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/Users/andrew_myers/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/Users/andrew_myers/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by afred** [comment]
redis wasn't running :unamused:
